#!/bin/bash
#ClearLinux Wifi
mkdir -vp /etc/wpa_supplicant/;
mkdir -vp /etc/systemd/network/;
wlan=$(networkctl list | grep wlan | awk '{print $2}');
echo "network={
    ssid=\"SSID\"
    psk=\"AwesomePassphrase\"
    scan_ssid=1
    priority=1
}" > /etc/wpa_supplicant/wpa_supplicant-"$wlan".conf;

echo "[Match]
Name=wl*

[Network]
DHCP=yes" > /etc/systemd/network/81-wireless-dhcp.network;

systemctl start "wpa_supplicant@$wlan.service";

systemctl restart systemd-networkd;


