#!/bin/bash
#postinstall scripts for bionic on bionic server
wget -O sources.list https://raw.githubusercontent.com/rico360z28/cheats/master/bionic-sources.list sources.list
sudo cp sources.list /etc/apt/sources.list
sudo apt update
sudo apt upgrade -y
sudo apt install ubuntu-desktop -y
sudo apt install nmap iftop htop screen nano -y
wget https://mesh.rrpcloud.com/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh && chmod 755 ./meshinstall.sh && sudo ./meshinstall.sh https://mesh.rrpcloud.com 'y$VTLSB4EHdLZ7@3TLpk22kNoDEDHot52D0nfmJaT15@8xvn@thIE$XLZ7XUWbu0'
sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y
sudo usermod -aG docker $USER
curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod a+x /usr/local/bin/docker-compose
